openapi: 3.0.0
info:
  version: 2019-12-03
  x-release: v4
  title: AWS Outposts Catalog Connections API
  description: Amazon Web Services Outposts is a fully managed service that extends Amazon Web Services infrastructure, APIs, and tools to customer premises. By providing local access to Amazon Web Services managed infrastructure, Amazon Web Services Outposts enables customers to build and run applications on premises using the same programming interfaces as in Amazon Web Services Regions, while using local compute and storage resources for lower latency and local data processing needs.
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: outposts
  x-aws-signingName: outposts
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/outposts-2019-12-03.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://outposts.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Outposts multi-region endpoint
- url: https://outposts.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The Outposts multi-region endpoint
- url: http://outposts.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Outposts endpoint for China (Beijing) and China (Ningxia)
- url: https://outposts.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The Outposts endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Connections
paths:
  /connections/{ConnectionId}:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: GetConnection
      description: <note> <p> Amazon Web Services uses this action to install Outpost servers.</p> </note> <p> Gets information about the specified connection. </p> <p> Use CloudTrail to monitor this action or Amazon Web Services managed policy for Amazon Web Services Outposts to secure it. For more information, see <a href="https://docs.aws.amazon.com/outposts/latest/userguide/security-iam-awsmanpol.html"> Amazon Web Services managed policies for Amazon Web Services Outposts</a> and <a href="https://docs.aws.amazon.com/outposts/latest/userguide/logging-using-cloudtrail.html"> Logging Amazon Web Services Outposts API calls with Amazon Web Services CloudTrail</a> in the <i>Amazon Web Services Outposts User Guide</i>. </p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetConnectionResponse'
              examples:
                GetConnection200Example:
                  summary: Default GetConnection 200 response
                  x-microcks-default: true
                  value:
                    ConnectionId: resource-abc123
                    ConnectionDetails: example-string
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '481':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '482':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      parameters:
      - name: ConnectionId
        in: path
        required: true
        description: ' The ID of the connection. '
        schema:
          type: string
          pattern: ^[a-zA-Z0-9+/=]{1,1024}$
          minLength: 1
          maxLength: 1024
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      summary: Amazon Outposts Get Connection
      tags:
      - Connections
  /connections:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: StartConnection
      description: <note> <p> Amazon Web Services uses this action to install Outpost servers.</p> </note> <p> Starts the connection required for Outpost server installation. </p> <p> Use CloudTrail to monitor this action or Amazon Web Services managed policy for Amazon Web Services Outposts to secure it. For more information, see <a href="https://docs.aws.amazon.com/outposts/latest/userguide/security-iam-awsmanpol.html"> Amazon Web Services managed policies for Amazon Web Services Outposts</a> and <a href="https://docs.aws.amazon.com/outposts/latest/userguide/logging-using-cloudtrail.html"> Logging Amazon Web Services Outposts API calls with Amazon Web Services CloudTrail</a> in the <i>Amazon Web Services Outposts User Guide</i>. </p>
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StartConnectionResponse'
              examples:
                StartConnection200Example:
                  summary: Default StartConnection 200 response
                  x-microcks-default: true
                  value:
                    ConnectionId: resource-abc123
                    UnderlayIpAddress: example-string
        '480':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '481':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '482':
          description: NotFoundException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundException'
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              - DeviceSerialNumber
              - AssetId
              - ClientPublicKey
              - NetworkInterfaceDeviceIndex
              properties:
                DeviceSerialNumber:
                  description: ' The serial number of the dongle. '
                  type: string
                  pattern: ^(\w+)$
                  minLength: 1
                  maxLength: 100
                AssetId:
                  description: ' The ID of the Outpost server. '
                  type: string
                  pattern: ^(\w+)$
                  minLength: 1
                  maxLength: 100
                ClientPublicKey:
                  description: ' The public key of the client. '
                  type: string
                  pattern: ^[a-zA-Z0-9/+]{43}=$
                  minLength: 44
                  maxLength: 44
                NetworkInterfaceDeviceIndex:
                  description: ' The device index of the network interface on the Outpost server. '
                  type: integer
                  minimum: 0
                  maximum: 1
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      summary: Amazon Outposts Start Connection
      tags:
      - Connections
components:
  parameters:
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
  schemas:
    UnderlayIpAddress:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
      minLength: 7
      maxLength: 15
    NotFoundException: {}
    StartConnectionResponse:
      type: object
      properties:
        ConnectionId:
          allOf:
          - $ref: '#/components/schemas/ConnectionId'
          - description: ' The ID of the connection. '
        UnderlayIpAddress:
          allOf:
          - $ref: '#/components/schemas/UnderlayIpAddress'
          - description: ' The underlay IP address. '
    AccessDeniedException: {}
    CIDR:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$
      minLength: 9
      maxLength: 18
    ConnectionId:
      type: string
      pattern: ^[a-zA-Z0-9+/=]{1,1024}$
      minLength: 1
      maxLength: 1024
    ServerEndpoint:
      type: string
      pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}:[0-9]{1,5}$
      minLength: 9
      maxLength: 21
    InternalServerException: {}
    CIDRList:
      type: array
      items:
        $ref: '#/components/schemas/CIDR'
    GetConnectionResponse:
      type: object
      properties:
        ConnectionId:
          allOf:
          - $ref: '#/components/schemas/ConnectionId'
          - description: ' The ID of the connection. '
        ConnectionDetails:
          allOf:
          - $ref: '#/components/schemas/ConnectionDetails'
          - description: ' Information about the connection. '
    ConnectionDetails:
      type: object
      properties:
        ClientPublicKey:
          allOf:
          - $ref: '#/components/schemas/WireGuardPublicKey'
          - description: ' The public key of the client. '
        ServerPublicKey:
          allOf:
          - $ref: '#/components/schemas/WireGuardPublicKey'
          - description: ' The public key of the server. '
        ServerEndpoint:
          allOf:
          - $ref: '#/components/schemas/ServerEndpoint'
          - description: ' The endpoint for the server. '
        ClientTunnelAddress:
          allOf:
          - $ref: '#/components/schemas/CIDR'
          - description: ' The client tunnel address. '
        ServerTunnelAddress:
          allOf:
          - $ref: '#/components/schemas/CIDR'
          - description: ' The server tunnel address. '
        AllowedIps:
          allOf:
          - $ref: '#/components/schemas/CIDRList'
          - description: ' The allowed IP addresses. '
      description: ' Information about a connection. '
    ValidationException: {}
    WireGuardPublicKey:
      type: string
      pattern: ^[a-zA-Z0-9/+]{43}=$
      minLength: 44
      maxLength: 44
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/outposts/
x-hasEquivalentPaths: true
